<script type="text/javascript" src="{{asset('vendor/jquery/jquery-1.12.3.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/tether/js/tether.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/detectmobilebrowser/detectmobilebrowser.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/jscrollpane/jquery.mousewheel.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/jscrollpane/mwheelIntent.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/jscrollpane/jquery.jscrollpane.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/waves/waves.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/chartist/chartist.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/switchery/dist/switchery.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/flot/jquery.flot.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/flot/jquery.flot.resize.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/flot.tooltip/js/jquery.flot.tooltip.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/CurvedLines/curvedLines.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/TinyColor/tinycolor.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/sparkline/jquery.sparkline.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/raphael/raphael.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/morris/morris.min.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/jvectormap/jquery-jvectormap-world-mill.js')}}"></script>
<script type="text/javascript" src="{{asset('vendor/jvectormap/jquery-jvectormap-world-mill.js')}}"></script>
@yield('scripts')
<script type="text/javascript" src="{{asset('js/app.js')}}"></script>